### ISSUE TITLE
Error InvalidTextureSize on iMac 27'' 5K

### ISSUE THREAD

**Issue by zuobaoquan** [lcnr/akari#2]
Just cloned the repository and `cargo run` failed with the error

Error: InvalidTextureSize { width: 128, height: 32 }

**Comment by lcnr** [comment]
this is probably https://github.com/lcnr/crow/issues/15,
updated to the latestcommit of `crow`, can you please try it again?

**Comment by zuobaoquan** [comment]
Thanks! I can run it now. but the background seems problem
 
<img width="1072" alt="Screen Shot 2020-03-11 at 5 09 57 PM" src="https://user-images.githubusercontent.com/740504/76400354-20e2f380-63bb-11ea-9474-849acb4f3eff.png">

**Comment by zuobaoquan** [comment]
Attached some log

> 
>  2020-03-11T09:11:13.323Z INFO  akari::environment > Loading chunk: (-1, -1)
>  2020-03-11T09:11:13.323Z INFO  akari::environment > Loading chunk: (-1, 0)
>  2020-03-11T09:11:13.323Z INFO  akari::environment > Loading chunk: (-1, 1)
>  2020-03-11T09:11:13.323Z INFO  akari::environment > Loading chunk: (0, -1)
>  2020-03-11T09:11:13.323Z INFO  akari::environment > Loading chunk: (0, 0)
>  2020-03-11T09:11:13.324Z INFO  akari::environment > Loading chunk: (0, 1)
>  2020-03-11T09:11:13.324Z INFO  akari::environment > Loading chunk: (1, -1)
>  2020-03-11T09:11:13.324Z INFO  akari::environment > Loading chunk: (1, 0)
>  2020-03-11T09:11:13.325Z INFO  akari::environment > Loading chunk: (1, 1)
>  2020-03-11T09:11:13.369Z WARN  akari::time        > Lag at frame 1
>  2020-03-11T09:11:13.399Z WARN  akari::time        > Lag at frame 2
>  2020-03-11T09:11:13.410Z WARN  akari::time        > Lag at frame 3
>  2020-03-11T09:11:13.414Z WARN  akari::time        > Lag at frame 4
>  2020-03-11T09:11:13.414Z WARN  akari::time        > Lag at frame 5
>  2020-03-11T09:11:32.609Z INFO  akari::environment > Loading chunk: (2, -1)
>  2020-03-11T09:11:32.609Z INFO  akari::environment > Loading chunk: (2, 0)
>  2020-03-11T09:11:32.609Z INFO  akari::environment > Loading chunk: (2, 1)
>  2020-03-11T09:12:44.411Z WARN  akari::environment::chunk > Dropped chunk without calling `Chunk::clear` first
>  2020-03-11T09:12:44.411Z WARN  akari::environment::chunk > Dropped chunk without calling `Chunk::clear` first
> ...

**Comment by lcnr** [comment]
Thanks, I finally know where HiDPI currently breaks.

This seems to depend on https://github.com/lcnr/crow/issues/4

**Comment by lcnr** [comment]
While this is not a complete fix, the most recent commit should hopefully fix your problem.

**Comment by zuobaoquan** [comment]
Thanks for the quick reply.  Here is the new image
<img width="1072" alt="Screen Shot 2020-03-11 at 6 05 19 PM" src="https://user-images.githubusercontent.com/740504/76405273-d8c7cf00-63c2-11ea-89db-191babef2883.png">

**Comment by lcnr** [comment]
`crow` adjusts the viewport to the screen size, which ignores HiDPI, will actually have to fix this in `crow` itself.

**Comment by lcnr** [comment]
Please try again, added a simple fix to `crow`.

**Comment by zuobaoquan** [comment]
Thanks! It looks OK now.
<img width="1072" alt="Screen Shot 2020-03-11 at 8 39 01 PM" src="https://user-images.githubusercontent.com/740504/76417711-50ecbf80-63d8-11ea-9341-1c5b2fc17d75.png">
